using System;
using System.Collections.Generic;
using System.Text;

namespace FsmAssembly
{
    public static class RandomNameGenerator
    {
        public static string GenerateName(ThreadSafeRandom rnd, int len = 5, int diffLen = 0)
        {
            len += rnd.Next(diffLen);
            if (len <= 0)
                return "";
            string name = "";
            bool nextLetterIsConsonant = rnd.Next(2) == 1;//Start with consonant or vowel
            while (name.Length < len)
            {
                name += pickLetter(rnd, nextLetterIsConsonant);
                nextLetterIsConsonant = !nextLetterIsConsonant;
            }
            //Check if begins with two of the same letter (consonants)
            if (name.Length >= 2 & name[0] == name[1])
            {
                name = name.Substring(2);
                while (name.Length < len)
                {
                    name += pickLetter(rnd, nextLetterIsConsonant);
                    nextLetterIsConsonant = !nextLetterIsConsonant;
                }
            }
            //clip the length if to long
            name = name.Substring(0, len);
            //Make first letter upper case
            name = name.Substring(0, 1).ToUpper() + name.Substring(1);
            return name;
        }

        private static string pickLetter(ThreadSafeRandom rnd, bool pickConsonant)
        {
            string[] consonants = { "b", "c", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "v", "w", "x", "z", "bb", "ck", "ch", "cr", "dd", "dr", "dl", "ff", "fr", "fl", "gg", "gr", "kl", "kn", "kr", "ll", "lk", "lr", "ls", "mm", "mn", "ml", "mr", "ms", "nn", "pp", "ph", "pl", "pr", "ps", "rr", "ss", "sh", "sl", "tt", "tr" };
            string[] vowels = { "a", "e", "i", "o", "u", "y", "ae", "ai", "ao", "au", "ei", "ia", "io", "oa", "ua", "ue", "ui", "uo" };
            if (pickConsonant)
                return consonants[rnd.Next(consonants.Length)];
            else
                return vowels[rnd.Next(vowels.Length)];
        }

        public static string PickStringFromList(ThreadSafeRandom rnd, StringListEnum stringList)
        {
            switch (stringList)
            {
                case StringListEnum.Gemstone:
                    return _gemstone[rnd.Next(_gemstone.Length)];
                case StringListEnum.Rock:
                    return _rock[rnd.Next(_rock.Length)];
                case StringListEnum.Animal:
                    return _animal[rnd.Next(_animal.Length)];
                case StringListEnum.Adjective:
                    return _adjective[rnd.Next(_adjective.Length)];
                case StringListEnum.Verb:
                    return _verb[rnd.Next(_verb.Length)];
                case StringListEnum.Color:
                    return _color[rnd.Next(_color.Length)];
                case StringListEnum.Wood:
                    return _wood[rnd.Next(_wood.Length)];
                default:
                    return "";
            }
        }
        //List of gemstones for generating names
        private static readonly string[] _gemstone =
        {
        "afghanite",
        "agate",
        "alexandrite",
        "amazonite",
        "amber",
        "amethyst",
        "ametrine",
        "ammolite",
        "andalusite",
        "andesine feldspar",
        "apatite",
        "aquamarine",
        "aventurine",
        "azurite",
        "azurite with malachite",
        "bastnasite",
        "beads",
        "benitoite",
        "beryl",
        "black star diopside",
        "bloodstone",
        "calcite",
        "calligraphy stone",
        "carnelian",
        "cavansite",
        "chalcedony",
        "charoite",
        "chrome diopside",
        "chrysanthemum flower stone",
        "chrysoberyl",
        "chrysocolla",
        "chrysoprase",
        "citrine",
        "coral",
        "danburite",
        "diamond",
        "diaspore",
        "dioptase",
        "druzy",
        "emerald",
        "eudialyte",
        "fire agate",
        "fluorite",
        "fuchsite",
        "garnet",
        "hackmanite",
        "heliodor",
        "hematite",
        "hiddenite",
        "howlite",
        "iolite",
        "ironstone",
        "jade",
        "jasper",
        "jeremejevite",
        "kunzite",
        "kyanite",
        "labradorite",
        "lapis lazuli",
        "larimar",
        "lava rock",
        "lazurite",
        "lepidolite",
        "magnetite",
        "malachite",
        "meteorite",
        "mexican fire opal",
        "moldavite",
        "moonstone",
        "morganite",
        "mystic quartz",
        "obsidian",
        "onyx",
        "opalite",
        "orthoclase",
        "pearl",
        "peridot",
        "petalite",
        "pietersite",
        "prasiolite",
        "prehnite",
        "pyrite",
        "quartz",
        "rhodochrosite",
        "rhodonite",
        "rhyolite",
        "ruby",
        "ruby & zoisite",
        "sapphire",
        "scapolite",
        "selenite",
        "septarian",
        "seraphinite",
        "serpentine",
        "shell stones",
        "shiva lingam",
        "sillimanite",
        "sodalite",
        "spectrolite",
        "sphalerite",
        "sphene",
        "spinel",
        "spodumene",
        "stichtite",
        "sugilite",
        "sunstone",
        "super seven",
        "tanzanite",
        "tektite",
        "tiffany stone",
        "tiger eye",
        "tiger iron",
        "topaz",
        "tourmaline",
        "tremolite",
        "triphane",
        "turkiyenite",
        "turquoise",
        "variscite",
        "verdite",
        "zebra stone",
        "zircon",
        "zoisite"
        };
        //List of rocks for generating names
        private static readonly string[] _rock =
        {
        "amphibolite",
        "andesite",
        "anorthosite",
        "aplite",
        "arkose",
        "banded iron formation",
        "basalt",
        "basanite",
        "blueschist",
        "breccia",
        "carbonatite",
        "charnockite",
        "chert",
        "clay",
        "coal",
        "concretion",
        "conglomerate",
        "coquina",
        "dacite",
        "diabase",
        "diatomite",
        "diorite",
        "dolomite",
        "dunite",
        "eclogite",
        "epidiorite",
        "epidosite",
        "essexite",
        "evaporite",
        "flint",
        "foidolite",
        "gabbro",
        "geode",
        "gneiss",
        "granite",
        "granodiorite",
        "granophyre",
        "granulite",
        "greywacke",
        "greenschist",
        "greenstone",
        "greenstone belts",
        "harzburgite",
        "hornblendite",
        "hornfels",
        "ignimbrite",
        "ijolite",
        "jasperoid",
        "jaspillite",
        "kimberlite",
        "komatiite",
        "lamproite",
        "lamprophyre",
        "latite",
        "lherzolite",
        "limestone",
        "luxullianite",
        "marble",
        "marl",
        "migmatite",
        "monzonite",
        "mudstone",
        "mylonite",
        "nepheline syenite",
        "nephelinite",
        "norite",
        "novaculite",
        "obsidian",
        "ophiolite",
        "pegmatite",
        "peridotite",
        "petoskey stone",
        "phonolite",
        "phyllite",
        "picrite",
        "porphyry",
        "pumice",
        "pseudotachylyte",
        "pyroclastic rock",
        "pyroxenite",
        "quartzite",
        "quartz monzonite",
        "rapakivi granite",
        "rhyodacite",
        "rhyolite",
        "rhomb porphyry",
        "sand",
        "sandstone",
        "schist",
        "scoria",
        "serpentinite",
        "shale",
        "siltstone",
        "skarn",
        "slate",
        "syenite",
        "tachylyte",
        "taconite",
        "tephrite",
        "theralite",
        "tonalite",
        "trachyte",
        "troctolite",
        "trondhjemite",
        "tuffite",
        "turbidite",
        "wackestone",
        "websterite",
        "wehrlite"
        };
        //List of adjectives to be used in naming
        private static readonly string[] _adjective =
        {
        "abandoned",
        "able",
        "absolute",
        "academic",
        "acceptable",
        "acclaimed",
        "accomplished",
        "accurate",
        "aching",
        "acidic",
        "acrobatic",
        "active",
        "actual",
        "adept",
        "admirable",
        "admired",
        "adolescent",
        "adorable",
        "adored",
        "advanced",
        "adventurous",
        "affectionate",
        "afraid",
        "aged",
        "aggravating",
        "aggressive",
        "agile",
        "agitated",
        "agonizing",
        "agreeable",
        "ajar",
        "alarmed",
        "alarming",
        "alert",
        "alienated",
        "alive",
        "all",
        "altruistic",
        "amazing",
        "ambitious",
        "ample",
        "amused",
        "amusing",
        "anchored",
        "ancient",
        "angelic",
        "angry",
        "anguished",
        "animated",
        "annual",
        "another",
        "antique",
        "anxious",
        "any",
        "apprehensive",
        "appropriate",
        "apt",
        "arctic",
        "arid",
        "aromatic",
        "artistic",
        "ashamed",
        "assured",
        "astonishing",
        "athletic",
        "attached",
        "attentive",
        "attractive",
        "austere",
        "authentic",
        "authorized",
        "automatic",
        "avaricious",
        "average",
        "aware",
        "awesome",
        "awful",
        "awkward",
        "babyish",
        "back",
        "bad",
        "baggy",
        "bare",
        "barren",
        "basic",
        "beautiful",
        "belated",
        "beloved",
        "beneficial",
        "best",
        "better",
        "bewitched",
        "big",
        "big-hearted",
        "biodegradable",
        "bite-sized",
        "bitter",
        "black",
        "black-and-white",
        "bland",
        "blank",
        "blaring",
        "bleak",
        "blind",
        "blissful",
        "blond",
        "blue",
        "blushing",
        "bogus",
        "boiling",
        "bold",
        "bony",
        "boring",
        "bossy",
        "both",
        "bouncy",
        "bountiful",
        "bowed",
        "brave",
        "breakable",
        "brief",
        "bright",
        "brilliant",
        "brisk",
        "broken",
        "bronze",
        "brown",
        "bruised",
        "bubbly",
        "bulky",
        "bumpy",
        "buoyant",
        "burdensome",
        "burly",
        "bustling",
        "busy",
        "buttery",
        "buzzing",
        "calculating",
        "calm",
        "candid",
        "canine",
        "capital",
        "carefree",
        "careful",
        "careless",
        "caring",
        "cautious",
        "cavernous",
        "celebrated",
        "charming",
        "cheap",
        "cheerful",
        "cheery",
        "chief",
        "chilly",
        "chubby",
        "circular",
        "classic",
        "clean",
        "clear",
        "clear-cut",
        "clever",
        "close",
        "closed",
        "cloudy",
        "clueless",
        "clumsy",
        "cluttered",
        "coarse",
        "cold",
        "colorful",
        "colorless",
        "colossal",
        "comfortable",
        "common",
        "compassionate",
        "competent",
        "complete",
        "complex",
        "complicated",
        "composed",
        "concerned",
        "concrete",
        "confused",
        "conscious",
        "considerate",
        "constant",
        "content",
        "conventional",
        "cooked",
        "cool",
        "cooperative",
        "coordinated",
        "corny",
        "corrupt",
        "costly",
        "courageous",
        "courteous",
        "crafty",
        "crazy",
        "creamy",
        "creative",
        "creepy",
        "criminal",
        "crisp",
        "critical",
        "crooked",
        "crowded",
        "cruel",
        "crushing",
        "cuddly",
        "cultivated",
        "cultured",
        "cumbersome",
        "curly",
        "curvy",
        "cute",
        "cylindrical",
        "damaged",
        "damp",
        "dangerous",
        "dapper",
        "daring",
        "dark",
        "darling",
        "dazzling",
        "dead",
        "deadly",
        "deafening",
        "dear",
        "dearest",
        "decent",
        "decimal",
        "decisive",
        "deep",
        "defenseless",
        "defensive",
        "defiant",
        "deficient",
        "definite",
        "definitive",
        "delayed",
        "delectable",
        "delicious",
        "delightful",
        "delirious",
        "demanding",
        "dense",
        "dental",
        "dependable",
        "dependent",
        "descriptive",
        "deserted",
        "detailed",
        "determined",
        "devoted",
        "different",
        "difficult",
        "digital",
        "diligent",
        "dim",
        "dimpled",
        "dimwitted",
        "direct",
        "dirty",
        "disastrous",
        "discrete",
        "disfigured",
        "disguised",
        "disgusting",
        "dishonest",
        "disloyal",
        "dismal",
        "distant",
        "distinct",
        "distorted",
        "dizzy",
        "dopey",
        "doting",
        "double",
        "downright",
        "drab",
        "drafty",
        "dramatic",
        "dreary",
        "droopy",
        "dry",
        "dual",
        "dull",
        "dutiful",
        "each",
        "eager",
        "early",
        "earnest",
        "easy",
        "easy-going",
        "ecstatic",
        "edible",
        "educated",
        "elaborate",
        "elastic",
        "elated",
        "elderly",
        "electric",
        "elegant",
        "elementary",
        "elliptical",
        "embarrassed",
        "embellished",
        "eminent",
        "emotional",
        "empty",
        "enchanted",
        "enchanting",
        "energetic",
        "enlightened",
        "enormous",
        "enraged",
        "entire",
        "envious",
        "equal",
        "equatorial",
        "essential",
        "esteemed",
        "ethical",
        "euphoric",
        "even",
        "evergreen",
        "everlasting",
        "every",
        "evil",
        "exalted",
        "excellent",
        "excitable",
        "excited",
        "exciting",
        "exemplary",
        "exhausted",
        "exotic",
        "expensive",
        "experienced",
        "expert",
        "extra-large",
        "extra-small",
        "extraneous",
        "extroverted",
        "fabulous",
        "failing",
        "faint",
        "fair",
        "faithful",
        "fake",
        "false",
        "familiar",
        "famous",
        "fancy",
        "fantastic",
        "far",
        "far-flung",
        "far-off",
        "faraway",
        "fast",
        "fat",
        "fatal",
        "fatherly",
        "favorable",
        "favorite",
        "fearful",
        "fearless",
        "feisty",
        "feline",
        "female",
        "feminine",
        "few",
        "fickle",
        "filthy",
        "fine",
        "finished",
        "firm",
        "first",
        "firsthand",
        "fitting",
        "fixed",
        "flaky",
        "flamboyant",
        "flashy",
        "flat",
        "flawed",
        "flawless",
        "flickering",
        "flimsy",
        "flippant",
        "flowery",
        "fluffy",
        "fluid",
        "flustered",
        "focused",
        "fond",
        "foolhardy",
        "foolish",
        "forceful",
        "forked",
        "formal",
        "forsaken",
        "forthright",
        "fortunate",
        "fragrant",
        "frail",
        "frank",
        "frayed",
        "free",
        "french",
        "frequent",
        "fresh",
        "friendly",
        "frightened",
        "frightening",
        "frigid",
        "frilly",
        "frivolous",
        "frizzy",
        "front",
        "frosty",
        "frozen",
        "frugal",
        "fruitful",
        "full",
        "fumbling",
        "functional",
        "funny",
        "fussy",
        "fuzzy",
        "gargantuan",
        "gaseous",
        "general",
        "generous",
        "gentle",
        "genuine",
        "giant",
        "giddy",
        "gifted",
        "gigantic",
        "giving",
        "glamorous",
        "glaring",
        "glass",
        "gleaming",
        "gleeful",
        "glistening",
        "glittering",
        "gloomy",
        "glorious",
        "glossy",
        "glum",
        "golden",
        "good",
        "good - natured",
        "gorgeous",
        "graceful",
        "gracious",
        "grand",
        "grandiose",
        "granular",
        "grateful",
        "grave",
        "gray",
        "great",
        "greedy",
        "green",
        "gregarious",
        "grim",
        "grimy",
        "gripping",
        "grizzled",
        "gross",
        "grotesque",
        "grouchy",
        "grounded",
        "growing",
        "growling",
        "grown",
        "grubby",
        "gruesome",
        "grumpy",
        "guilty",
        "gullible",
        "gummy",
        "hairy",
        "half",
        "handmade",
        "handsome",
        "handy",
        "happy",
        "happy - go - lucky",
        "hard",
        "hard - to - find",
        "harmful",
        "harmless",
        "harmonious",
        "harsh",
        "hasty",
        "hateful",
        "haunting",
        "healthy",
        "heartfelt",
        "hearty",
        "heavenly",
        "heavy",
        "hefty",
        "helpful",
        "helpless",
        "hidden",
        "hideous",
        "high",
        "high - level",
        "hilarious",
        "hoarse",
        "hollow",
        "homely",
        "honest",
        "honorable",
        "honored",
        "hopeful",
        "horrible",
        "hospitable",
        "hot",
        "huge",
        "humble",
        "humiliating",
        "humming",
        "humongous",
        "hungry",
        "hurtful",
        "husky",
        "i",
        "icky",
        "icy",
        "ideal",
        "idealistic",
        "identical",
        "idiotic",
        "idle",
        "idolized",
        "ignorant",
        "ill",
        "ill - fated",
        "ill - informed",
        "illegal",
        "illiterate",
        "illustrious",
        "imaginary",
        "imaginative",
        "immaculate",
        "immaterial",
        "immediate",
        "immense",
        "impartial",
        "impassioned",
        "impeccable",
        "imperfect",
        "imperturbable",
        "impish",
        "impolite",
        "important",
        "impossible",
        "impractical",
        "impressionable",
        "impressive",
        "improbable",
        "impure",
        "inborn",
        "incomparable",
        "incompatible",
        "incomplete",
        "inconsequential",
        "incredible",
        "indelible",
        "indolent",
        "inexperienced",
        "infamous",
        "infantile",
        "infatuated",
        "inferior",
        "infinite",
        "informal",
        "innocent",
        "insecure",
        "insidious",
        "insignificant",
        "insistent",
        "instructive",
        "insubstantial",
        "intelligent",
        "intent",
        "intentional",
        "interesting",
        "internal",
        "international",
        "intrepid",
        "ironclad",
        "irresponsible",
        "irritating",
        "itchy",
        "jaded",
        "jagged",
        "jam-packed",
        "jaunty",
        "jealous",
        "jittery",
        "joint",
        "jolly",
        "jovial",
        "joyful",
        "joyous",
        "jubilant",
        "judicious",
        "juicy",
        "jumbo",
        "jumpy",
        "junior",
        "juvenile",
        "kaleidoscopic",
        "keen",
        "key",
        "kind",
        "kindhearted",
        "kindly",
        "klutzy",
        "knobby",
        "knotty",
        "knowing",
        "knowledgeable",
        "known",
        "kooky",
        "kosher",
        "lame",
        "lanky",
        "large",
        "last",
        "lasting",
        "late",
        "lavish",
        "lawful",
        "lazy",
        "leading",
        "leafy",
        "lean",
        "left",
        "legal",
        "legitimate",
        "light",
        "lighthearted",
        "likable",
        "likely",
        "limited",
        "limp",
        "limping",
        "linear",
        "lined",
        "liquid",
        "little",
        "live",
        "lively",
        "livid",
        "loathsome",
        "lone",
        "lonely",
        "long",
        "long-term",
        "loose",
        "lopsided",
        "lost",
        "loud",
        "lovable",
        "lovely",
        "loving",
        "low",
        "loyal",
        "lucky",
        "lumbering",
        "luminous",
        "lumpy",
        "lustrous",
        "luxurious",
        "mad",
        "made-up",
        "magnificent",
        "majestic",
        "major",
        "male",
        "mammoth",
        "married",
        "marvelous",
        "masculine",
        "massive",
        "mature",
        "meager",
        "mealy",
        "mean",
        "measly",
        "meaty",
        "medical",
        "mediocre",
        "medium",
        "meek",
        "mellow",
        "melodic",
        "memorable",
        "menacing",
        "merry",
        "messy",
        "metallic",
        "mild",
        "milky",
        "mindless",
        "miniature",
        "minor",
        "minty",
        "miserable",
        "miserly",
        "misguided",
        "misty",
        "mixed",
        "modern",
        "modest",
        "moist",
        "monstrous",
        "monthly",
        "monumental",
        "moral",
        "mortified",
        "motherly",
        "motionless",
        "mountainous",
        "muddy",
        "muffled",
        "multicolored",
        "mundane",
        "murky",
        "mushy",
        "musty",
        "muted",
        "mysterious",
        "naive",
        "narrow",
        "nasty",
        "natural",
        "naughty",
        "nautical",
        "near",
        "neat",
        "necessary",
        "needy",
        "negative",
        "neglected",
        "negligible",
        "neighboring",
        "nervous",
        "new",
        "next",
        "nice",
        "nifty",
        "nimble",
        "nippy",
        "nocturnal",
        "noisy",
        "nonstop",
        "normal",
        "notable",
        "noted",
        "noteworthy",
        "novel",
        "noxious",
        "numb",
        "nutritious",
        "nutty",
        "obedient",
        "obese",
        "oblong",
        "obvious",
        "occasional",
        "odd",
        "oddball",
        "offbeat",
        "offensive",
        "official",
        "oily",
        "old",
        "old-fashioned",
        "only",
        "open",
        "optimal",
        "optimistic",
        "opulent",
        "orange",
        "orderly",
        "ordinary",
        "organic",
        "original",
        "ornate",
        "ornery",
        "other",
        "our",
        "outgoing",
        "outlandish",
        "outlying",
        "outrageous",
        "outstanding",
        "oval",
        "overcooked",
        "overdue",
        "overjoyed",
        "overlooked",
        "palatable",
        "pale",
        "paltry",
        "parallel",
        "parched",
        "partial",
        "passionate",
        "past",
        "pastel",
        "peaceful",
        "peppery",
        "perfect",
        "perfumed",
        "periodic",
        "perky",
        "personal",
        "pertinent",
        "pesky",
        "pessimistic",
        "petty",
        "phony",
        "physical",
        "piercing",
        "pink",
        "pitiful",
        "plain",
        "plaintive",
        "plastic",
        "playful",
        "pleasant",
        "pleased",
        "pleasing",
        "plump",
        "plush",
        "pointed",
        "pointless",
        "poised",
        "polished",
        "polite",
        "political",
        "poor",
        "popular",
        "portly",
        "posh",
        "positive",
        "possible",
        "potable",
        "powerful",
        "powerless",
        "practical",
        "precious",
        "present",
        "prestigious",
        "pretty",
        "previous",
        "pricey",
        "prickly",
        "primary",
        "prime",
        "pristine",
        "private",
        "prize",
        "probable",
        "productive",
        "profitable",
        "profuse",
        "proper",
        "proud",
        "prudent",
        "punctual",
        "pungent",
        "puny",
        "pure",
        "purple",
        "pushy",
        "putrid",
        "puzzled",
        "puzzling",
        "quaint",
        "qualified",
        "quarrelsome",
        "quarterly",
        "queasy",
        "querulous",
        "questionable",
        "quick",
        "quick-witted",
        "quiet",
        "quintessential",
        "quirky",
        "quixotic",
        "quizzical",
        "radiant",
        "ragged",
        "rapid",
        "rare",
        "rash",
        "raw",
        "ready",
        "real",
        "realistic",
        "reasonable",
        "recent",
        "reckless",
        "rectangular",
        "red",
        "reflecting",
        "regal",
        "regular",
        "reliable",
        "relieved",
        "remarkable",
        "remorseful",
        "remote",
        "repentant",
        "repulsive",
        "required",
        "respectful",
        "responsible",
        "revolving",
        "rewarding",
        "rich",
        "right",
        "rigid",
        "ringed",
        "ripe",
        "roasted",
        "robust",
        "rosy",
        "rotating",
        "rotten",
        "rough",
        "round",
        "rowdy",
        "royal",
        "rubbery",
        "ruddy",
        "rude",
        "rundown",
        "runny",
        "rural",
        "rusty",
        "sad",
        "safe",
        "salty",
        "same",
        "sandy",
        "sane",
        "sarcastic",
        "sardonic",
        "satisfied",
        "scaly",
        "scarce",
        "scared",
        "scary",
        "scented",
        "scholarly",
        "scientific",
        "scornful",
        "scratchy",
        "scrawny",
        "second",
        "second-hand",
        "secondary",
        "secret",
        "self-assured",
        "self-reliant",
        "selfish",
        "sentimental",
        "separate",
        "serene",
        "serious",
        "serpentine",
        "several",
        "severe",
        "shabby",
        "shadowy",
        "shady",
        "shallow",
        "shameful",
        "shameless",
        "sharp",
        "shimmering",
        "shiny",
        "shocked",
        "shocking",
        "shoddy",
        "short",
        "short-term",
        "showy",
        "shrill",
        "shy",
        "sick",
        "silent",
        "silky",
        "silly",
        "silver",
        "similar",
        "simple",
        "simplistic",
        "sinful",
        "single",
        "sizzling",
        "skeletal",
        "skinny",
        "sleepy",
        "slight",
        "slim",
        "slimy",
        "slippery",
        "slow",
        "slushy",
        "small",
        "smart",
        "smoggy",
        "smooth",
        "smug",
        "snappy",
        "snarling",
        "sneaky",
        "sniveling",
        "snoopy",
        "sociable",
        "soft",
        "soggy",
        "solid",
        "somber",
        "some",
        "sophisticated",
        "sore",
        "sorrowful",
        "soulful",
        "soupy",
        "sour",
        "spanish",
        "sparkling",
        "sparse",
        "specific",
        "spectacular",
        "speedy",
        "spherical",
        "spicy",
        "spiffy",
        "spirited",
        "spiteful",
        "splendid",
        "spotless",
        "spotted",
        "spry",
        "square",
        "squeaky",
        "squiggly",
        "stable",
        "staid",
        "stained",
        "stale",
        "standard",
        "starchy",
        "stark",
        "starry",
        "steel",
        "steep",
        "sticky",
        "stiff",
        "stimulating",
        "stingy",
        "stormy",
        "straight",
        "strange",
        "strict",
        "strident",
        "striking",
        "striped",
        "strong",
        "studious",
        "stunning",
        "stupendous",
        "stupid",
        "sturdy",
        "stylish",
        "subdued",
        "submissive",
        "substantial",
        "subtle",
        "suburban",
        "sudden",
        "sugary",
        "sunny",
        "super",
        "superb",
        "superficial",
        "superior",
        "supportive",
        "sure-footed",
        "surprised",
        "suspicious",
        "svelte",
        "sweaty",
        "sweet",
        "sweltering",
        "swift",
        "sympathetic",
        "talkative",
        "tall",
        "tame",
        "tan",
        "tangible",
        "tart",
        "tasty",
        "tattered",
        "taut",
        "tedious",
        "teeming",
        "tempting",
        "tender",
        "tense",
        "tepid",
        "terrible",
        "terrific",
        "testy",
        "thankful",
        "that",
        "these",
        "thick",
        "thin",
        "third",
        "thirsty",
        "this",
        "thorny",
        "thorough",
        "those",
        "thoughtful",
        "threadbare",
        "thrifty",
        "thunderous",
        "tidy",
        "tight",
        "timely",
        "tinted",
        "tiny",
        "tired",
        "torn",
        "total",
        "tough",
        "tragic",
        "trained",
        "traumatic",
        "treasured",
        "tremendous",
        "triangular",
        "tricky",
        "trifling",
        "trim",
        "trivial",
        "troubled",
        "true",
        "trusting",
        "trustworthy",
        "trusty",
        "truthful",
        "tubby",
        "turbulent",
        "twin",
        "ugly",
        "ultimate",
        "unacceptable",
        "unaware",
        "uncomfortable",
        "uncommon",
        "unconscious",
        "understated",
        "unequaled",
        "uneven",
        "unfinished",
        "unfit",
        "unfolded",
        "unfortunate",
        "unhappy",
        "unhealthy",
        "uniform",
        "unimportant",
        "unique",
        "united",
        "unkempt",
        "unknown",
        "unlawful",
        "unlined",
        "unlucky",
        "unnatural",
        "unpleasant",
        "unrealistic",
        "unripe",
        "unruly",
        "unselfish",
        "unsightly",
        "unsteady",
        "unsung",
        "untidy",
        "untimely",
        "untried",
        "untrue",
        "unused",
        "unusual",
        "unwelcome",
        "unwieldy",
        "unwilling",
        "unwitting",
        "unwritten",
        "upbeat",
        "upright",
        "upset",
        "urban",
        "usable",
        "used",
        "useful",
        "useless",
        "utilized",
        "utter",
        "vacant",
        "vague",
        "vain",
        "valid",
        "valuable",
        "vapid",
        "variable",
        "vast",
        "velvety",
        "venerated",
        "vengeful",
        "verifiable",
        "vibrant",
        "vicious",
        "victorious",
        "vigilant",
        "vigorous",
        "villainous",
        "violent",
        "violet",
        "virtual",
        "virtuous",
        "visible",
        "vital",
        "vivacious",
        "vivid",
        "voluminous",
        "wan",
        "warlike",
        "warm",
        "warmhearted",
        "warped",
        "wary",
        "wasteful",
        "watchful",
        "waterlogged",
        "watery",
        "wavy",
        "weak",
        "wealthy",
        "weary",
        "webbed",
        "wee",
        "weekly",
        "weepy",
        "weighty",
        "weird",
        "welcome",
        "well-documented",
        "well-groomed",
        "well-informed",
        "well-lit",
        "well-made",
        "well-off",
        "well-to-do",
        "well-worn",
        "wet",
        "which",
        "whimsical",
        "whirlwind",
        "whispered",
        "white",
        "whole",
        "whopping",
        "wicked",
        "wide",
        "wide-eyed",
        "wiggly",
        "wild",
        "willing",
        "wilted",
        "winding",
        "windy",
        "winged",
        "wiry",
        "wise",
        "witty",
        "wobbly",
        "woeful",
        "wonderful",
        "wooden",
        "woozy",
        "wordy",
        "worldly",
        "worn",
        "worried",
        "worrisome",
        "worse",
        "worst",
        "worthless",
        "worthwhile",
        "worthy",
        "wrathful",
        "wretched",
        "writhing",
        "wrong",
        "wry",
        "yawning",
        "yearly",
        "yellow",
        "yellowish",
        "young",
        "youthful",
        "yummy",
        "zany",
        "zealous",
        "zesty",
        "zigzag"
        };
        //list of animals to use for naming
        private static readonly string[] _animal =
        {
        "ardvark",
        "aardwolf",
        "accentor",
        "acouchi",
        "addax",
        "african buffalo",
        "african wild ass",
        "african wild dog",
        "agama",
        "agouti",
        "albatross",
        "alligator",
        "alpaca",
        "american black bear",
        "american sparrow",
        "amur leopard",
        "anaconda",
        "andean mountain cat",
        "anemone",
        "angelfish",
        "anhinga",
        "anoa",
        "anole",
        "ant",
        "anteater",
        "antelope",
        "archerfish",
        "arctic fox",
        "armadillo",
        "arowana",
        "asian black bear",
        "auk",
        "avocet",
        "axolotl",
        "aye-aye",
        "babirusa",
        "baboon",
        "badger",
        "bald eagle",
        "bandicoot",
        "banteng",
        "barbet",
        "basilisk",
        "bat",
        "batfish",
        "bear",
        "bearded dragon",
        "beaver",
        "bed bug",
        "bee",
        "bee-eater",
        "beetle",
        "betta",
        "bettong",
        "bigeyes",
        "bilby",
        "binturong",
        "bird",
        "bird-of-paradise",
        "bison",
        "bitterling",
        "bittern",
        "black-footed cat",
        "black-footed ferret",
        "blackdevil",
        "blue sheep",
        "blue whale",
        "bluebird",
        "boa",
        "bobcat",
        "bongo",
        "booby",
        "bowerbird",
        "brat",
        "broadbill",
        "brown bear",
        "budgie",
        "bulbul",
        "bull",
        "bullfrog",
        "bunny",
        "bunting",
        "bush dog",
        "bushbaby",
        "bushshrike",
        "bustard",
        "butterfly",
        "buzzard",
        "caecilian",
        "camel",
        "capybara",
        "caracal",
        "caracara",
        "cardinal",
        "cardinalfish",
        "caribou",
        "carp",
        "cassowary",
        "cat",
        "caterpillar",
        "catfish",
        "cattle",
        "cavy",
        "centipede",
        "chameleon",
        "chamois",
        "chat",
        "cheetah",
        "chicken",
        "chimaera",
        "chimpanzee",
        "chinchilla",
        "chipmunk",
        "chough",
        "chuckwalla",
        "cicada",
        "cichlid",
        "civet",
        "clam",
        "climbing mouse",
        "climbing perch",
        "clouded leopard",
        "clownfish",
        "coati",
        "cobra",
        "cockatiel",
        "cockatoo",
        "cockroach",
        "cocanth",
        "colugo",
        "common genet",
        "conch",
        "coot",
        "copperhead",
        "cormorant",
        "cotinga",
        "cotton rat",
        "cougar",
        "courser",
        "cow",
        "coyote",
        "coypu",
        "crab",
        "crane",
        "crane fly",
        "crayfish",
        "cricket",
        "crocodile",
        "crow",
        "cuckoo",
        "culpeo",
        "curlew",
        "cuscus",
        "cuttlefish",
        "dartfish",
        "dassie rat",
        "death adder",
        "deer",
        "deer mouse",
        "degu",
        "dhole",
        "dibbler",
        "dik-dik",
        "dikkop",
        "dimetrodon",
        "dingo",
        "dinosaur",
        "dipper",
        "discus",
        "dodo",
        "dog",
        "dolphin",
        "donkey",
        "dormouse",
        "dove",
        "dragonfly",
        "drongo",
        "duck",
        "dugong",
        "duiker",
        "dunnart",
        "eagle",
        "eagle ray",
        "echidna",
        "eel",
        "egret",
        "eider",
        "electric eel",
        "electric ray",
        "elephant",
        "elephant bird",
        "elk",
        "emu",
        "ermine",
        "falcon",
        "fennec fox",
        "ferret",
        "finch",
        "fish",
        "fisher",
        "fishing cat",
        "flamingo",
        "flat-headed cat",
        "flea",
        "flowerpecker",
        "fly",
        "flying fish",
        "flying frog",
        "fossa",
        "fox",
        "frigatebird",
        "frog",
        "frogmouth",
        "fulmar",
        "galago",
        "gallinule",
        "gannet",
        "gar",
        "garter snake",
        "gaur",
        "gazelle",
        "gecko",
        "geoffroy's cat",
        "gerbil",
        "gerenuk",
        "giant panda",
        "giant tortoise",
        "gibbon",
        "gila monster",
        "giraffe",
        "gnu",
        "goat",
        "goatfish",
        "goldfish",
        "goose",
        "gopher",
        "goral",
        "gorilla",
        "gourami",
        "grackle",
        "grasshopper",
        "greater glider",
        "grebe",
        "green iguana",
        "grison",
        "grizzly bear",
        "groundhog",
        "grouse",
        "guanaco",
        "guinea pig",
        "gull",
        "gundi",
        "hamster",
        "harrier",
        "hartebeest",
        "hawaiian honeycreeper",
        "hawk",
        "hawkodile",
        "hawkodile",
        "hedgehog",
        "helmetshrike",
        "hermit crab",
        "heron",
        "himalayan tahr",
        "hippopotamus",
        "hissing cockroach",
        "honeyeater",
        "hornbill",
        "hornet",
        "horse",
        "hoverfly",
        "hummingbird",
        "hutia",
        "hyena",
        "hyrax",
        "iberian lynx",
        "ibex",
        "ibis",
        "icterid",
        "iguana",
        "impala",
        "insect",
        "jacana",
        "jack",
        "jackal",
        "jaguar",
        "jaguarundi",
        "jay",
        "jellyfish",
        "jerboa",
        "jungle cat",
        "kangaroo",
        "kangaroo rat",
        "kangolf",
        "kerodon",
        "kestrel",
        "king cobra",
        "kingbird",
        "kingfisher",
        "kinkajou",
        "kite",
        "kitten",
        "kiwi",
        "klipspringer",
        "knifefish",
        "koala",
        "kodiak bear",
        "kodkod",
        "koi",
        "komodo dragon",
        "kookaburra",
        "kowari",
        "kudu",
        "kultarr",
        "ladybug",
        "lamb",
        "lamprey",
        "lapwing",
        "leech",
        "lemming",
        "lemur",
        "leopard",
        "liger",
        "lion",
        "lionfish",
        "liun",
        "lizard",
        "llama",
        "loach",
        "lobster",
        "long-tailed tit",
        "longspur",
        "loon",
        "loris",
        "lory",
        "lovebird",
        "lynx",
        "lyrebird",
        "macaw",
        "magpie",
        "mallard",
        "mamba",
        "mammoth",
        "manakin",
        "manatee",
        "mandrill",
        "manta ray",
        "mantis shrimp",
        "mara",
        "margay",
        "marine angelfish",
        "marine hatchetfish",
        "markhor",
        "marlin",
        "marmot",
        "marsupial mole",
        "marten",
        "mastodon",
        "meadowlark",
        "meerkat",
        "megaloceros",
        "megapode",
        "millipede",
        "miniature horse",
        "mink",
        "minnow",
        "mockingbird",
        "mole",
        "mole rat",
        "mongoose",
        "monitor lizard",
        "monkey",
        "moorhen",
        "moose",
        "moray eel",
        "mosasaur",
        "mosquito",
        "moth",
        "motmot",
        "mountain goat",
        "mountain lion",
        "mouse",
        "mouse deer",
        "mousebird",
        "mudpuppy",
        "mudskipper",
        "mullet",
        "muntjac",
        "muskox",
        "muskrat",
        "musky rat-kangaroo",
        "naked mole-rat",
        "narwhal",
        "nautilus",
        "needlefish",
        "newt",
        "nighthawk",
        "nightjar",
        "numbat",
        "nuthatch",
        "nutria",
        "ocelot",
        "octopus",
        "okapi",
        "old world babbler",
        "old world flycatcher",
        "olingo",
        "onager",
        "opossum",
        "orangutan",
        "orca",
        "oriole",
        "oryx",
        "osprey",
        "ostrich",
        "otter",
        "ovenbird",
        "owl",
        "oyster",
        "paca",
        "paddlefish",
        "pademelon",
        "pallas's cat",
        "panda",
        "pangolin",
        "panther",
        "parakeet",
        "parrot",
        "parrotfish",
        "passenger pigeon",
        "peacock",
        "peafowl",
        "peccary",
        "pelican",
        "penguin",
        "pheasant",
        "pig",
        "pigeon",
        "pika",
        "pike",
        "piranha",
        "pitohui",
        "pizzly bear",
        "platypus",
        "plover",
        "pocket gopher",
        "pogona",
        "poison dart frog",
        "polar bear",
        "pony",
        "porcupine",
        "porpoise",
        "possum",
        "potoo",
        "potoroo",
        "potto",
        "pouched rat",
        "prairie dog",
        "prawn",
        "praying mantis",
        "pronghorn",
        "przewalski's horse ",
        "ptarmigan",
        "pterosaur",
        "pudu",
        "puff adder",
        "puffer fish",
        "puffin",
        "puma",
        "puppy",
        "python",
        "qinling panda",
        "quagga",
        "quail",
        "quetzal",
        "quokka",
        "quoll",
        "rabbit",
        "raccoon",
        "raccoon dog",
        "rail",
        "rainbowfish",
        "rat",
        "rattlesnake",
        "raven",
        "red panda",
        "red river hog",
        "reindeer",
        "rhea",
        "rhinoceros",
        "ringtail",
        "river dolphin",
        "roadrunner",
        "robin",
        "rock hyrax",
        "rockfish",
        "roller",
        "rook",
        "rufous rat-kangaroo",
        "saber-toothed cat",
        "sailfish",
        "salamander",
        "salmon",
        "sand cat",
        "sandgrouse",
        "sawfish",
        "scorpion",
        "sea anemone",
        "sea cucumber",
        "sea duck",
        "sea gull",
        "sea lion",
        "sea otter",
        "sea snake",
        "seadragon",
        "seahorse",
        "seal",
        "serval",
        "shark",
        "shearwater",
        "sheep",
        "shelduck",
        "shoebill",
        "shrew",
        "shrimp",
        "skate",
        "skimmer",
        "skink",
        "skua",
        "skunk",
        "sloth",
        "sloth bear",
        "slow loris",
        "slug",
        "snail",
        "snake",
        "snipe",
        "snow leopard",
        "solenodon",
        "songbird",
        "sparrow",
        "spectacled bear",
        "spider",
        "spiny lobster",
        "spiny mouse",
        "spiny rat",
        "sponge",
        "spoonbill",
        "springhare",
        "squid",
        "squirrel",
        "squirrel glider",
        "starfish",
        "starling",
        "steppe lemming",
        "stick bug",
        "stingray",
        "stoat",
        "stone-curlew",
        "stonefish",
        "stork",
        "sturgeon",
        "sun bear",
        "sunbird",
        "surgeonfish",
        "swallow",
        "swamphen",
        "swan",
        "swift",
        "swordfish",
        "tadpole",
        "takin",
        "tamandua",
        "tamarin",
        "tanager",
        "tapaculo",
        "tapir",
        "tarantula",
        "tarpon",
        "tarsier",
        "tasmanian devil",
        "tasmanian wolf",
        "tayra",
        "tenrec",
        "termite",
        "tern",
        "tetra",
        "thick-knee",
        "thornbill",
        "thrasher",
        "thrush",
        "tiger",
        "tit",
        "toad",
        "toadfish",
        "tortoise",
        "toucan",
        "treeshrew",
        "t-rex",
        "trogon",
        "trout",
        "trumpeter",
        "tuatara",
        "tuna",
        "turaco",
        "turkey",
        "turtle",
        "tyrant flycatcher",
        "urchin",
        "vanga",
        "vaquita",
        "vicuna",
        "viper",
        "viscacha",
        "vole",
        "vulture",
        "wader",
        "wagtail",
        "wallaby",
        "walleye",
        "walrus",
        "wapiti",
        "warbler",
        "warthog",
        "wasp",
        "water buffalo",
        "waxwing",
        "weasel",
        "weaver",
        "weaver-finch",
        "whale",
        "whistler",
        "whistling duck",
        "white-eye",
        "whydah",
        "widow spider",
        "wigeon",
        "wildcat",
        "wildebeest",
        "wolf",
        "wolverine",
        "wombat",
        "wongai ningaui",
        "woodchuck",
        "woodcock",
        "woodpecker",
        "woodswallow",
        "worm",
        "wren",
        "x-ray tetra",
        "xenopoecilus",
        "xenops",
        "xerus",
        "yak",
        "yapok",
        "yellowjacket",
        "zebra",
        "zebu"
        };
        //list of verbs to use for naming
        private static readonly string[] _verb =
        {
        "abashing",
        "abating",
        "abiding",
        "absorbing",
        "accepting",
        "accompanying",
        "aching",
        "achieving",
        "acquiring",
        "acting",
        "adding",
        "addressing",
        "adjusting",
        "admiring",
        "admitting",
        "advising",
        "affording",
        "agreeing",
        "alighting",
        "allowing",
        "animating",
        "announcing",
        "answering",
        "apologizing",
        "appearing",
        "applauding",
        "applying",
        "approaching",
        "approving",
        "arguing",
        "arising",
        "arranging",
        "arresting",
        "asking",
        "asserting",
        "assorting",
        "astonishing",
        "attacking",
        "attending",
        "attracting",
        "auditing",
        "avoiding",
        "awaking",
        "banging",
        "banishing",
        "bashing",
        "batting",
        "being",
        "bearing",
        "bearing",
        "beating",
        "beautifying",
        "becoming",
        "befalling",
        "begging",
        "beginning",
        "behaving",
        "beholding",
        "believing",
        "belonging",
        "bending",
        "bereaving",
        "beseeching",
        "betting",
        "betraying",
        "bidding",
        "bidding",
        "binding",
        "biting",
        "bleeding",
        "blessing",
        "blossoming",
        "blowing",
        "blurring",
        "blushing",
        "boarding",
        "boasting",
        "boiling",
        "bowing",
        "boxing",
        "braying",
        "breaking",
        "breathing",
        "breeding",
        "bringing",
        "broadcasting",
        "brushing",
        "building",
        "burning",
        "bursting",
        "burying",
        "busting",
        "buying",
        "buzzing",
        "calculating",
        "calling",
        "canvassing",
        "capturing",
        "caressing",
        "carrying",
        "carving",
        "cashing",
        "casting",
        "catching",
        "causing",
        "ceasing",
        "celebrating",
        "challenging",
        "changing",
        "charging",
        "chasing",
        "chatting",
        "checking",
        "cheering",
        "chewing",
        "chiding",
        "chipping",
        "choking",
        "choosing",
        "classifying",
        "cleaning",
        "cleaving",
        "clicking",
        "climbing",
        "clinging",
        "closing",
        "clothing",
        "clutching",
        "collapsing",
        "collecting",
        "colouring",
        "coming",
        "commenting",
        "comparing",
        "compelling",
        "competing",
        "complaining",
        "completing",
        "concluding",
        "conducting",
        "confessing",
        "confining",
        "confiscating",
        "confusing",
        "congratulating",
        "connecting",
        "connoting",
        "conquering",
        "consecrating",
        "consenting",
        "conserving",
        "considering",
        "consigning",
        "consisting",
        "consoling",
        "consorting",
        "conspiring",
        "constituting",
        "constraining",
        "constructing",
        "construing",
        "consulting",
        "containing",
        "contemning",
        "contending",
        "contesting",
        "continuing",
        "contracting",
        "contradicting",
        "contrasting",
        "contributing",
        "contriving",
        "controlling",
        "convening",
        "converging",
        "conversing",
        "converting",
        "conveying",
        "convicting",
        "convincing",
        "cooing",
        "cooking",
        "cooling",
        "co-operating",
        "coping",
        "copying",
        "correcting",
        "corresponding",
        "corroding",
        "corrupting",
        "costing",
        "coughing",
        "counselling",
        "counting",
        "coursing",
        "covering",
        "cowering",
        "cracking",
        "crackling",
        "crashing",
        "craving",
        "creating",
        "creeping",
        "cribbing",
        "crossing",
        "crowding",
        "crushing",
        "crying",
        "curbing",
        "curing",
        "curving",
        "cutting",
        "cycling",
        "damaging",
        "damping",
        "dancing",
        "daring",
        "dashing",
        "dazzling",
        "dealing",
        "decaying",
        "deciding",
        "declaring",
        "decorating",
        "decreasing",
        "dedicating",
        "delaying",
        "deleting",
        "denying",
        "depending",
        "depriving",
        "deriving",
        "describing",
        "desiring",
        "destroying",
        "detaching",
        "detecting",
        "determining",
        "developing",
        "dying",
        "differing",
        "digging",
        "digesting",
        "dimming",
        "diminishing",
        "dining",
        "dipping",
        "directing",
        "disappearing",
        "discovering",
        "discussing",
        "disobeying",
        "displaying",
        "disposing",
        "distributing",
        "disturbing",
        "disusing",
        "diving",
        "dividing",
        "doing",
        "donating",
        "downloading",
        "dragging",
        "drawing",
        "dreaming",
        "dressing",
        "drilling",
        "drinking",
        "driving",
        "dropping",
        "drying",
        "dumping",
        "dwelling",
        "dyeing",
        "earning",
        "eating",
        "educating",
        "empowering",
        "emptying",
        "encircling",
        "encouraging",
        "encroaching",
        "entangling",
        "endorsing",
        "enduring",
        "engraving",
        "enjoying",
        "enlarging",
        "enlightening",
        "entering",
        "envying",
        "erasing",
        "escaping",
        "evaporating",
        "exchanging",
        "exclaiming",
        "excluding",
        "existing",
        "expanding",
        "expecting",
        "explaining",
        "exploring",
        "expressing",
        "extending",
        "eyeing",
        "facing",
        "failing",
        "fainting",
        "falling",
        "fanning",
        "fancying",
        "favouring",
        "faxing",
        "feeding",
        "feeling",
        "ferrying",
        "fetching",
        "fighting",
        "filling",
        "finding",
        "finishing",
        "fishing",
        "fitting",
        "fixing",
        "fizzing",
        "flapping",
        "flashing",
        "fleeing",
        "flinging",
        "floating",
        "flopping",
        "flying",
        "folding",
        "following",
        "forbidding",
        "forcing",
        "forecasting",
        "foretelling",
        "forgetting",
        "forgiving",
        "forlesing",
        "forming",
        "forsaking",
        "founding",
        "framing",
        "freeing",
        "freezing",
        "frightening",
        "frying",
        "fulfilling",
        "gagging",
        "gaining",
        "gainsaying",
        "gashing",
        "gazing",
        "getting",
        "giving",
        "glancing",
        "glittering",
        "glowing",
        "going",
        "googling",
        "governing",
        "grabbing",
        "grading",
        "granting",
        "greeting",
        "grinding",
        "gripping",
        "growing",
        "guarding",
        "guessing",
        "guiding",
        "handling",
        "hanging",
        "happening",
        "harming",
        "hatching",
        "hating",
        "having",
        "healing",
        "hearing",
        "heaving",
        "helping",
        "hewing",
        "hiding",
        "hindering",
        "hissing",
        "hitting",
        "hoaxing",
        "holding",
        "hopping",
        "hoping",
        "horrifying",
        "hugging",
        "humming",
        "humiliating",
        "hunting",
        "hurling",
        "hurrying",
        "hurting",
        "hushing",
        "hustling",
        "hypnotizing",
        "idealizing",
        "identifying",
        "idolizing",
        "igniting",
        "ignoring",
        "ill-treating",
        "illuminating",
        "illumining",
        "illustrating",
        "imagining",
        "imbibing",
        "imitating",
        "immersing",
        "immolating",
        "immuring",
        "impairing",
        "imparting",
        "impeaching",
        "impeding",
        "impelling",
        "impending",
        "imperilling",
        "impinging",
        "implanting",
        "implicating",
        "imploding",
        "imploring",
        "implying",
        "importing",
        "imposing",
        "impressing",
        "imprinting",
        "imprisoning",
        "improving",
        "inaugurating",
        "incising",
        "including",
        "increasing",
        "inculcating",
        "indenting",
        "indicating",
        "inducing",
        "indulging",
        "infecting",
        "infesting",
        "inflaming",
        "inflating",
        "inflecting",
        "informing",
        "infringing",
        "infusing",
        "ingesting",
        "inhabiting",
        "inhaling",
        "inheriting",
        "initiating",
        "injecting",
        "injuring",
        "inlaying",
        "innovating",
        "inputting",
        "inquiring",
        "inscribing",
        "inserting",
        "inspecting",
        "inspiring",
        "installing",
        "insulting",
        "insuring",
        "integrating",
        "introducing",
        "inventing",
        "inviting",
        "joining",
        "jumping",
        "justifying",
        "keeping",
        "kicking",
        "kidding",
        "killing",
        "kissing",
        "kneeling",
        "knitting",
        "knocking",
        "knowing",
        "lading",
        "landing",
        "lasting",
        "latching",
        "laughing",
        "laying",
        "leading",
        "leaking",
        "leaning",
        "leaping",
        "learning",
        "leaving",
        "leering",
        "lending",
        "letting",
        "licking",
        "lying",
        "lying",
        "lifting",
        "lighting",
        "liking",
        "limping",
        "listening",
        "living",
        "looking",
        "losing",
        "loving",
        "magnifying",
        "maintaining",
        "making",
        "managing",
        "marching",
        "marking",
        "marrying",
        "mashing",
        "matching",
        "mattering",
        "meaning",
        "measuring",
        "meeting",
        "melting",
        "merging",
        "mewing",
        "migrating",
        "milking",
        "minding",
        "misleading",
        "missing",
        "mistaking",
        "misusing",
        "mixing",
        "moaning",
        "modifying",
        "mooing",
        "motivating",
        "moulding",
        "moulting",
        "moving",
        "mowing",
        "multiplying",
        "murmuring",
        "nailing",
        "napping",
        "needing",
        "neglecting",
        "nipping",
        "nodding",
        "noting",
        "noticing",
        "notifying",
        "nourishing",
        "nursing",
        "obeying",
        "obliging",
        "observing",
        "obstructing",
        "obtaining",
        "occupying",
        "occurring",
        "offering",
        "offsetting",
        "omitting",
        "oozing",
        "opening",
        "operating",
        "opining",
        "oppressing",
        "opting",
        "optimizing",
        "ordering",
        "organizing",
        "originating",
        "outputting",
        "overflowing",
        "overtaking",
        "owing",
        "owning",
        "pacifying",
        "painting",
        "pardoning",
        "parting",
        "partaking",
        "participating",
        "passing",
        "pasting",
        "patting",
        "patching",
        "pausing",
        "paying",
        "peeping",
        "perishing",
        "permitting",
        "persuading",
        "phoning",
        "placing",
        "planning",
        "playing",
        "pleading",
        "pleasing",
        "plodding",
        "plotting",
        "plucking",
        "plying",
        "pointing",
        "polishing",
        "polluting",
        "pondering",
        "pouring",
        "pouting",
        "practising",
        "praising",
        "praying",
        "preaching",
        "preferring",
        "preparing",
        "prescribing",
        "presenting",
        "preserving",
        "presetting",
        "presiding",
        "pressing",
        "pretending",
        "preventing",
        "printing",
        "proceeding",
        "producing",
        "progressing",
        "prohibiting",
        "promising",
        "proposing",
        "prosecuting",
        "protecting",
        "proving",
        "providing",
        "pulling",
        "punishing",
        "purifying",
        "pushing",
        "putting",
        "qualifying",
        "quarrelling",
        "questioning",
        "quitting",
        "racing",
        "raining",
        "rattling",
        "reaching",
        "reading",
        "realizing",
        "rebuilding",
        "recalling",
        "recasting",
        "receiving",
        "reciting",
        "recognizing",
        "recollecting",
        "recurring",
        "redoing",
        "reducing",
        "referring",
        "reflecting",
        "refusing",
        "regarding",
        "regretting",
        "relating",
        "relaxing",
        "relying",
        "remaining",
        "remaking",
        "removing",
        "rending",
        "renewing",
        "renouncing",
        "repairing",
        "repeating",
        "replacing",
        "replying",
        "reporting",
        "requesting",
        "reselling",
        "resembling",
        "resetting",
        "resisting",
        "resolving",
        "respecting",
        "resting",
        "restraining",
        "retaining",
        "retching",
        "retiring",
        "returning",
        "reusing",
        "reviewing",
        "rewinding",
        "ridding",
        "riding",
        "ringing",
        "rising",
        "roaring",
        "robbing",
        "rolling",
        "rotting",
        "rubbing",
        "ruling",
        "running",
        "rushing",
        "sabotaging",
        "sacking",
        "sacrificing",
        "saddening",
        "saddling",
        "sagging",
        "sailing",
        "sallying",
        "saluting",
        "salvaging",
        "salving",
        "sampling",
        "sanctifying",
        "sanctioning",
        "sapping",
        "saponifying",
        "sashing",
        "sashaying",
        "sassing",
        "sating",
        "satiating",
        "satirising",
        "satisfying",
        "saturating",
        "sauntering",
        "saving",
        "savoring",
        "savvying",
        "sawing",
        "saying",
        "scabbing",
        "scabbling",
        "scalding",
        "scaling",
        "scamming",
        "scanning",
        "scanting",
        "scarring",
        "scaring",
        "scarifying",
        "scarping",
        "scatting",
        "scattering",
        "scolding",
        "scorching",
        "scowling",
        "scrawling",
        "screaming",
        "screwing",
        "scrubbing",
        "searching",
        "seating",
        "securing",
        "seeing",
        "seeking",
        "seeming",
        "seizing",
        "selecting",
        "selling",
        "sending",
        "sentencing",
        "separating",
        "setting",
        "severing",
        "sewing",
        "shaking",
        "shaping",
        "sharing",
        "shattering",
        "shaving",
        "shearing",
        "shedding",
        "shining",
        "shirking",
        "shitting",
        "shivering",
        "shocking",
        "shoeing",
        "shooting",
        "shortening",
        "shouting",
        "showing",
        "shrinking",
        "shunning",
        "shutting",
        "sighting",
        "signalling",
        "signifying",
        "singing",
        "sinking",
        "sipping",
        "sitting",
        "skiing",
        "skidding",
        "slamming",
        "slaying",
        "sleeping",
        "sliding",
        "slimming",
        "slinging",
        "slinking",
        "slipping",
        "slitting",
        "smashing",
        "smelling",
        "smiling",
        "smiting",
        "smoothing",
        "smothering",
        "snapping",
        "snatching",
        "sneaking",
        "sneezing",
        "sniffing",
        "soaring",
        "sobbing",
        "soliciting",
        "solving",
        "soothing",
        "sorting",
        "sowing",
        "sparkling",
        "speaking",
        "speeding",
        "spelling",
        "spending",
        "spilling",
        "spinning",
        "spitting",
        "splitting",
        "spoiling",
        "spraying",
        "spreading",
        "springing",
        "sprouting",
        "squeezing",
        "standing",
        "staring",
        "starting",
        "stating",
        "staying",
        "stealing",
        "steeping",
        "stemming",
        "stepping",
        "sterilizing",
        "sticking",
        "stimulating",
        "stinging",
        "stinking",
        "stirring",
        "stitching",
        "stooping",
        "stopping",
        "storing",
        "straining",
        "straying",
        "stressing",
        "stretching",
        "strewing",
        "striding",
        "striking",
        "stringing",
        "striving",
        "studying",
        "submitting",
        "subscribing",
        "subtracting",
        "succeeding",
        "sucking",
        "suffering",
        "suggesting",
        "summoning",
        "supplying",
        "supporting",
        "supposing",
        "surging",
        "surmising",
        "surpassing",
        "surrounding",
        "surveying",
        "surviving",
        "swallowing",
        "swaying",
        "swearing",
        "sweating",
        "sweeping",
        "swelling",
        "swimming",
        "swinging",
        "swotting",
        "taking",
        "talking",
        "tapping",
        "tasting",
        "taxing",
        "teaching",
        "tearing",
        "teeing",
        "telling",
        "tempting",
        "tending",
        "terminating",
        "terrifying",
        "testing",
        "thanking",
        "thinking",
        "thriving",
        "throwing",
        "thrusting",
        "thumping",
        "tying",
        "tiring",
        "tossing",
        "touching",
        "training",
        "trampling",
        "transferring",
        "transforming",
        "translating",
        "trapping",
        "travelling",
        "treading",
        "treasuring",
        "treating",
        "treeing",
        "trembling",
        "triumphing",
        "trusting",
        "trying",
        "turning",
        "typing",
        "typesetting",
        "understanding",
        "undoing",
        "uprooting",
        "upsetting",
        "urging",
        "using",
        "uttering",
        "valuing",
        "vanishing",
        "varying",
        "verifying",
        "vexing",
        "vying",
        "viewing",
        "violating",
        "vomiting",
        "waking",
        "walking",
        "wandering",
        "wanting",
        "warning",
        "wasting",
        "watching",
        "watering",
        "waving",
        "waxing",
        "waylaying",
        "wearing",
        "weaving",
        "wedding",
        "weeping",
        "weighing",
        "welcoming",
        "wending",
        "wetting",
        "whipping",
        "whispering",
        "winning",
        "winding",
        "wishing",
        "withdrawing",
        "working",
        "worrying",
        "worshipping",
        "wringing",
        "writing",
        "yawning",
        "yelling",
        "yielding",
        "zincking",
        "zooming"
        };
        //list of colors to use for naming
        private static readonly string[] _color =
        {
        "alizarin",
        "amaranth",
        "amber",
        "amethyst",
        "apricot",
        "aqua",
        "aquamarine",
        "asparagus",
        "auburn",
        "azure",
        "beige",
        "bistre",
        "black",
        "blue",
        "blue green",
        "blue violet",
        "bondi blue",
        "brass",
        "bronze",
        "brown",
        "buff",
        "burgundy",
        "burnt orange",
        "burnt sienna",
        "burnt umber",
        "camouflage green",
        "caput mortuum",
        "cardinal",
        "carmine",
        "carrot orange",
        "celadon",
        "cerise",
        "cerulean",
        "champagne",
        "charcoal",
        "chartreuse",
        "cherry blossom pink",
        "chestnut",
        "chocolate",
        "cinnabar",
        "cinnamon",
        "cobalt",
        "copper",
        "coral",
        "corn",
        "cornflower",
        "cream",
        "crimson",
        "cyan",
        "dandelion",
        "denim",
        "ecru",
        "emerald",
        "eggplant",
        "falu red",
        "fern green",
        "firebrick",
        "flax",
        "forest green",
        "french rose",
        "fuchsia",
        "gamboge",
        "gold",
        "goldenrod",
        "green",
        "grey",
        "han purple",
        "harlequin",
        "heliotrope",
        "hollywood cerise",
        "indigo",
        "ivory",
        "jade",
        "kelly green",
        "khaki",
        "lavender",
        "lawn green",
        "lemon",
        "lemon chiffon",
        "lilac",
        "lime",
        "lime green",
        "linen",
        "magenta",
        "magnolia",
        "malachite",
        "maroon",
        "mauve",
        "midnight blue",
        "mint green",
        "misty rose",
        "moss green",
        "mustard",
        "myrtle",
        "navajo white",
        "navy blue",
        "ochre",
        "office green",
        "olive",
        "olivine",
        "orange",
        "orchid",
        "papaya whip",
        "peach",
        "pear",
        "periwinkle",
        "persimmon",
        "pine green",
        "pink",
        "platinum",
        "plum",
        "powder blue",
        "puce",
        "prussian blue",
        "psychedelic purple",
        "pumpkin",
        "purple",
        "quartz grey",
        "raw umber",
        "razzmatazz",
        "red",
        "robin egg blue",
        "rose",
        "royal blue",
        "royal purple",
        "ruby",
        "russet",
        "rust",
        "safety orange",
        "saffron",
        "salmon",
        "sandy brown",
        "sangria",
        "sapphire",
        "scarlet",
        "school bus yellow",
        "sea green",
        "seashell",
        "sepia",
        "shamrock green",
        "shocking pink",
        "silver",
        "sky blue",
        "slate grey",
        "smalt",
        "spring bud",
        "spring green",
        "steel blue",
        "tan",
        "tangerine",
        "taupe",
        "teal",
        "tenné(tawny)",
        "terra cotta",
        "thistle",
        "titanium white",
        "tomato",
        "turquoise",
        "tyrian purple",
        "ultramarine",
        "van dyke brown",
        "vermilion",
        "violet",
        "viridian",
        "wheat",
        "white",
        "wisteria",
        "xanthic",
        "yellow",
        "zucchini"
        };
        //list of woodss to use for naming
        private static readonly string[] _wood =
        {
        "hoop pine",
        "monkey puzzle tree",
        "paraná pine",
        "cedar",
        "celery-top pine",
        "arizona cypress",
        "bald cypress",
        "alerce",
        "hinoki cypress",
        "lawson's cypress",
        "mediterranean cypress",
        "coast douglas-fir",
        "rocky mountain douglas-fir",
        "european yew",
        "balsam fir",
        "silver fir",
        "noble fir",
        "pacific silver fir",
        "eastern hemlock",
        "mountain hemlock",
        "western hemlock",
        "huon pine",
        "kauri",
        "queensland kauri",
        "japanese nutmeg-yew",
        "european larch",
        "japanese larch",
        "tamarack",
        "western larch",
        "european black pine",
        "jack pine",
        "lodgepole pine",
        "monterey pine",
        "ponderosa pine",
        "red pine",
        "scots pine",
        "eastern white pine",
        "western white pine",
        "sugar pine",
        "loblolly pine",
        "longleaf pine",
        "pitch pine",
        "shortleaf pine",
        "eastern red cedar",
        "western red cedar",
        "coast redwood",
        "rimu",
        "spruce",
        "norway spruce",
        "black spruce",
        "red spruce",
        "sitka spruce",
        "white spruce",
        "sugi",
        "northern white cedar",
        "atlantic white cedar",
        "nootka cypress",
        "abachi",
        "acacia",
        "african padauk",
        "afzelia",
        "agba",
        "black alder",
        "red alder",
        "american boi",
        "ash",
        "black ash",
        "blue ash",
        "common ash",
        "green ash",
        "oregon ash",
        "pumpkin ash",
        "white ash",
        "bigtooth aspen",
        "european aspen",
        "quaking aspen",
        "australian red cedar",
        "ayan",
        "balsa",
        "american basswood",
        "white basswood",
        "american beech",
        "gray birch",
        "black birch",
        "paper birch",
        "sweet birch",
        "yellow birch",
        "silver birch",
        "downy birch",
        "blackbean",
        "black tupelo",
        "australian blackwood",
        "african blackwood",
        "bloodwood",
        "boxelder",
        "boxwood",
        "brazilian walnut",
        "brazilwood",
        "gumbo limbo",
        "horse-chestnut",
        "ohio buckeye",
        "yellow buckeye",
        "butternut",
        "california bay laurel",
        "camphor tree",
        "cape chestnut",
        "catalpa",
        "ceylon satinwood",
        "black cherry",
        "red cherry",
        "wild cherry",
        "coachwood",
        "cocobolo",
        "corkwood",
        "balsam poplar",
        "eastern cottonwood",
        "swamp cottonwood",
        "cucumbertree",
        "flowering dogwood",
        "pacific dogwood",
        "andaman marblewood",
        "ebène marbre",
        "african ebony",
        "ceylon ebony",
        "american elm",
        "english elm",
        "rock elm",
        "slippery elm",
        "wych elm",
        "lyptus: flooded gum",
        "white mahogany",
        "brown mallet",
        "banglay",
        "river red gum",
        "karri",
        "blue gum",
        "flooded gum",
        "york gum",
        "jarrah",
        "tallowwood",
        "grey ironbark",
        "blackbutt",
        "mountain ash",
        "australian oak",
        "alpine ash",
        "red mahogany",
        "swamp mahogany",
        "sydney blue gum",
        "mugga",
        "redwood",
        "wandoo",
        "european crabapple",
        "european pear",
        "gonçalo alves",
        "greenheart",
        "grenadilla",
        "guanandi",
        "gum",
        "hackberry",
        "pecan",
        "pignut hickory",
        "shagbark hickory",
        "shellbark hickory",
        "hornbeam",
        "american hophornbeam",
        "iroko",
        "balau",
        "american hornbeam",
        "sheoak",
        "giant ironwood",
        "diesel tree",
        "borneo ironwood",
        "guaiacwood",
        "holywood",
        "takian",
        "ipê",
        "black ironwood",
        "lebombo ironwood",
        "catalina ironwood",
        "ceylon ironwood",
        "olive",
        "desert ironwood",
        "persian ironwood",
        "brazilian ironwood",
        "yellow lapacho",
        "jacarandá-boca-de-sapo",
        "jacarandá de brasil",
        "jatobá",
        "kingwood",
        "northern silky oak",
        "american sycamore",
        "london plane",
        "limba",
        "black locust",
        "honey locust",
        "west indies mahogany",
        "bigleaf mahogany",
        "pacific coast mahogany",
        "african mahogany",
        "chinese mahogany",
        "australian red cedar",
        "philippine mahogany",
        "indonesian mahogany",
        "sapele",
        "sipo",
        "tiama",
        "kosipo",
        "mountain mahogany",
        "indian mahogany",
        "spanish cedar",
        "light bosse",
        "dark bosse",
        "american muskwood",
        "carapa",
        "bead-tree",
        "sugar maple",
        "black maple",
        "boxelder",
        "red maple",
        "silver maple",
        "sycamore maple",
        "marblewood",
        "marri",
        "meranti",
        "merbau",
        "white oak",
        "bur oak",
        "post oak",
        "swamp white oak",
        "southern live oak",
        "swamp chestnut oak",
        "chestnut oak",
        "chinkapin oak",
        "canyon live oak",
        "overcup oak",
        "english oak",
        "northern red oak",
        "eastern black oak",
        "laurel oak",
        "southern red oak",
        "water oak",
        "willow oak",
        "nuttall's oak",
        "okoumé",
        "olive",
        "pink ivory",
        "balsam poplar",
        "black poplar",
        "hybrid black poplar",
        "tulip tree",
        "purpleheart",
        "queensland maple",
        "queensland walnut",
        "ramin",
        "redheart",
        "śāl",
        "sweetgum",
        "sandalwood",
        "indian sandalwood",
        "sassafras",
        "southern sassafras",
        "satiné",
        "silky oak",
        "silver wattle",
        "sourwood",
        "spanish-cedar",
        "spanish elm",
        "tamboti",
        "teak",
        "thailand rosewood",
        "tupelo",
        "turpentine",
        "eastern black walnut",
        "common walnut",
        "panga-panga",
        "black willow",
        "cricket-bat willow",
        "white willow",
        "weeping willow",
        "zingana",
        "bamboo",
        "coconut timber",
        "toddy palm timber"
        };
    }
}

